### ISSUE TITLE
How would I change the font size of items in lists, such as movie titles?

### ISSUE THREAD

**Issue by captain-caveman** [Nessus85100/Bello#48]
I want to increase the font size of list items, specifically movie titles. I've looked through a number of the xml files, but have not been able to determine where this change needs to be made. Any help is appreciated.

**Comment by Nessus85100** [comment]
If you mean the ListView the code for the videos ListView titles is here...
https://github.com/Nessus85100/Bello/blob/master/720p/ViewsVideos.xml#L546
https://github.com/Nessus85100/Bello/blob/master/720p/ViewsVideos.xml#L674

**Comment by captain-caveman** [comment]
That was exactly what I needed. Thanks a million!
