### ISSUE TITLE
Tumbnails view text overlapped

### ISSUE THREAD

**Issue by peppesr** [Nessus85100/Bello#52]
using the thumbnails view the text, if titles are too long, result overlapped. see image attached.
http://i59.tinypic.com/20azyid.jpg
Peppe

**Comment by Nessus85100** [comment]
Thanks buddy. Will fix it in the next update.

Cheers
Nessus

**Comment by peppesr** [comment]
ok mate,
while you are looking at this could you tell me if the fact that if i set thumbnails view on youtube addon and each time i exit and come back i find the list view, depend from bello or from the addon.
in the youtube settings i have as view id 500, same one as confluence for thumbnails  view.
tnx
Peppe

**Comment by Nessus85100** [comment]
It happens me too some times, but it works fine when i go in for second time. I think it's a YouTube Addon thing. The thumbnails view id in Bello is 560. Did you try that ?.

Cheers
Nessus

**Comment by peppesr** [comment]
i used id 560 and now seems to work all, but not the first level of the addon. subscriptions, search etc. are always in list view and if i change to thumbnails they come back to previous type.
could you tell me where find all the skin id so i can turn them to bromix.
have a nice day
Peppe

**Comment by Nessus85100** [comment]
Sorry for the delay. Here you can find all the views id's... https://github.com/Nessus85100/Bello/blob/master/720p/IncludesViews.xml#L10. I am closing this issue since it was fixed in v3.0.2
