### ISSUE TITLE
ERROR: ExecuteAsync - Not executing non-existing script script.skin.info.service

### ISSUE THREAD

**Issue by zandegran** [Nessus85100/Bello#59]
[https://discourse.osmc.tv/t/rpi2-update-04-04-2016-alternating-frown-and-dark-screen-after-update/15289/12?u=zandegran](https://discourse.osmc.tv/t/rpi2-update-04-04-2016-alternating-frown-and-dark-screen-after-update/15289/12?u=zandegran)

When I reboot with this skin, I's stuck. Please take a look at the thread.

**Comment by Nessus85100** [comment]
Last working version of Bello was for Helix. There is no Isengard version and as you read in the announcement there will be no Jarvis too. Bello is not dumped. It's just not free (or for private use) anymore. Sorry but, as i explain in forum's announcement, i can't do otherwise.
